version: 2

jobs:
  build:
    docker:
      - image: alpine:3.5
    working_directory: /iroha-python

    steps:
      - run:
          name: Install system-wide packages
          command: apk add --no-cache --no-progress cmake curl g++ git ninja openssh python2-dev python3-dev

      - checkout

      - run:
          name: Install flatc
          command: |
            set -ex
            FBVER='1.6.0'
            curl --output fb.tar.gz --location --silent --show-error https://github.com/google/flatbuffers/archive/v${FBVER}.tar.gz
            tar -xzf fb.tar.gz
            cmake -GNinja -Hflatbuffers-${FBVER} -Bflatbuffers-build
            cmake --build flatbuffers-build --target flatc
            cp flatbuffers-build/flatc /usr/local/bin
            rm -rf fb.tar.gz flatbuffers-${FBVER} flatbuffers-build

      - run:
          name: Install tox
          command: pip3 install tox

      - run:
          name: Generate FlatBufers schema
          command: python3 setup.py genfbs

      - run:
          name: Run tests
          command: tox

